# Generated by Django 5.0 on 2026-04-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_customuser_company_name_customuser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprofile',
            name='platform_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
