# Generated by Django 5.0 on 2026-04-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_post_author_name_post_parent_post_reaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api_app.post',),
        ),
        migrations.AddField(
            model_name='paymenttxn',
            name='plan_selected',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenttxn',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='paymenttxn',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttxn',
            name='method',
            field=models.CharField(default='bank_transfer', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenttxn',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttxn',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
