# Generated by Django 5.0 on 2026-05-24 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_comment_paymenttxn_plan_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentresult',
            name='confidence_score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='sentimentresult',
            name='engine_used',
            field=models.CharField(default='Local Lexicon', max_length=100),
        ),
        migrations.AddField(
            model_name='sentimentresult',
            name='is_sarcastic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentimentresult',
            name='sarcasm_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentresult',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='api_app.aimodel'),
        ),
    ]
